@url = http://localhost:3003

### TEST
GET {{url}}

### LOGIN JAMES
GET {{url}}/login/ja

### LOGIN ASHLEY
GET {{url}}/login/ac

### BAD LOGIN
GET {{url}}/login/nnn

### GET LOGGED IN USER
GET {{url}}/user

### LOGOUT 
GET {{url}}/logout

